### ISSUE TITLE
Entire dataset for reproduction

### ISSUE THREAD

**Issue by MurrayC7** [pkorus/neural-imaging#1]
Hi! 
Thanks for the open-source code. It's a really nice job.
I want to reproduce all results in the paper, so could you please provide the entire dataset if possible?
My email address is chencai@std.uestc.edu.cn. Thanks a lot :)

Best wishes,
Murray

**Comment by pkorus** [comment]
Hi Murray, I've posted the images that I was using on Google drive: 
https://drive.google.com/drive/folders/1swgfu3kjv6Pw8fVnnEqM8QD4xqwUG3EB?usp=sharing

I've split the data into separate files for each of the cameras. The data is fairly heavy, and hence don't rely on this link being available indefinitely. 

Let me know if you have issues with accessing Google's servers.

**Comment by MurrayC7** [comment]
Ok, thank you very much!
